# Generated by Django 5.2.1 on 2025-11-20 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('B', 'Basura'), ('A', 'Alumbrado'), ('V', 'Baches'), ('S', 'Seguridad'), ('O', 'Otros')], max_length=1)),
                ('ubicacion', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('E', 'En Progreso'), ('R', 'Resuelto')], default='P', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
